import React from "react";

const ThesisCard = () => {
    return (
      <div style={{
        backgroundColor: '#fdfefe',
        border: '1px solid #ccc',
        borderRadius: '12px',
        padding: '1.5rem',
        maxWidth: '500px',
        margin: '2rem auto',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.05)',
        textAlign: 'justify'
      }}>
        <h2 style={{ fontSize: '1.5rem', color: '#34495E', marginBottom: '1rem' }}>📘 Master's Thesis</h2>
        <h3 style={{ fontSize: '1.2rem', color: '#48C9B0', marginBottom: '0.5rem' }}>
          Title: A workflow for predictive modeling of WQIs and time-series forecasting using ensemble ML techniques on real-world incomplete data
        </h3>
        <p style={{ 
            fontSize: '1rem',
            lineHeight: '1.6',
            display: '-webkit-box',
            WebkitLineClamp: 5,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden',    
            textOverflow: 'ellipsis' 
    }}>
            Water quality assessment is a cornerstone of public health and environmental policy, founded on adherence to stipulated water quality standards 
            established by regulatory agencies. Additionally, analyzing changes in water quality is significant for various stakeholders, including local governments 
            and water utility providers. Since their inception in the 1960s, water quality index (WQI) models have become popular tools for evaluating surface water quality. 
            These indices are generated by normalizing, aggregating, and weighing a basket of water quality indicators, making it easy to communicate a single value or index. 
            Although WQIs are not universal metrics, many are based on common parameters such as pH, turbidity, total dissolved solids (TDS), and 
            nitrogen. Each WQI is tailored to specific regulatory needs, such as those defined by the Pennsylvania Department of Environmental Protection, 
            with metrics varying according to use cases. In this proposal, we aim to formulate a WQI model based on the Canadian Council of Ministers of the Environment (CCME) 
            for data collected from both open and proprietary sources. This model will help us better understand the relationship between underlying water quality parameters and 
            the final WQI value, allowing for effective grouping of sampling sites' health. Furthermore, by employing time series decomposition analysis, we can study underlying 
            patterns in water quality. Utilizing ensemble machine learning algorithms, we will forecast non-regular time-series WQI values, addressing the challenge of incomplete 
            data.
        </p>
        <a
          href="https://etda.libraries.psu.edu/catalog/29380rzd5485"
          target="_blank"
          style={{
            display: 'inline-block',
            marginTop: '1rem',
            padding: '8px 16px',
            backgroundColor: '#48C9B0',
            color: '#fff',
            borderRadius: '5px',
            textDecoration: 'none'
          }}
        >
          📄 Read More
        </a>
      </div>
    );
  };
  
export default ThesisCard;
